image: node:latest

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
